version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container-movie-reservation
    restart: always
    environment:
      POSTGRES_DB: db_movie_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: